version: '3.4'

services:
    climat-control.backend:
        image: climat-control.backend:dev
        build:
            context: ./backend
            dockerfile: ./HomeClimatControl.Web/Dockerfile
        ports:
            - 5000:80
        devices:
            - "/dev/ttyUSB0":"/dev/ttyUSB0"
    climat-control.webapp:
        image: climat-control.webapp:dev
        build: ./web-app
        ports:
            - 5001:80