version: '3.4'

services:
    backend:
        build:
            context: ./backend
            dockerfile: ./HomeClimatControl.Web/Dockerfile
        ports:
            - 5000:80
    webapp:
        build: ./web-app
        ports:
            - 5001:80